name: storybook_flutter
description: A storybook for Flutter widgets. Live preview of isolated widgets for faster development and showcase.
version: 0.1.5
homepage: https://github.com/ookami-kb/storybook_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  provider: ">=4.3.2 <5.0.0"
  recase: ">=2.0.1 <4.0.0"
  rxdart: ">=0.24.0 <1.0.0"

dev_dependencies:
  build_runner: ^1.10.10
  flutter_test:
    sdk: flutter
  freezed: ^0.12.6

flutter:
  uses-material-design: true
